# Disk layout as generated by nixos-generate-config.
{
  flake.modules.nixos."hosts/frieren" =
    {
      lib,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "usb_storage"
        "sdhci_pci"
      ];
      boot.initrd.luks.devices."cryptroot".device =
        "/dev/disk/by-uuid/162e3f71-01e3-4f58-8567-1f5748529e66";

      fileSystems."/" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        options = [ "subvol=@" ];
      };

      fileSystems."/nix" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        options = [ "subvol=@nix" ];
      };

      fileSystems."/persist" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        options = [ "subvol=@persist" ];
      };

      fileSystems."/home" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        options = [ "subvol=@home" ];
      };

      fileSystems."/var/log" = {
        device = "/dev/mapper/cryptroot";
        fsType = "btrfs";
        options = [ "subvol=@log" ];
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/7B3A-1725";
        fsType = "vfat";
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
      };

      nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
    };
}
